/*SCRIPT DE BANCO DE DADOS DO ARTIGO LINQ TO SQL DA EASY .NET MAGAZINE EDIÇÃO 31 - Julho 2013
Autor: Luís Gabriel N. Simas
Data/Hora Início: 06/07/2013 - 23:00
Data/Hora Término: 07/07/2013 - 04:30
*/
/*Criação e uso do Banco de Dados*/
CREATE DATABASE MVCSeguranca
GO

USE MVCSeguranca
GO

/* Criação das Tabelas */
CREATE TABLE Usuario(
	Id			INT	IDENTITY,
	IdPerfil	INT,
	IdCliente	INT,
	Login		VARCHAR(200) NOT NULL,
	Senha		VARCHAR(20) NOT NULL,
)
GO

ALTER TABLE Usuario ADD CONSTRAINT PK_Usuario PRIMARY KEY(Id)
ALTER TABLE Usuario ADD CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY(IdPerfil) REFERENCES Perfil(Id)
ALTER TABLE Usuario ADD CONSTRAINT FK_USUARIO_CLIENTE FOREIGN KEY(IdCliente) REFERENCES Cliente(Id)
GO

DROP TABLE Usuario
GO

CREATE TABLE Perfil(
	Id		INT IDENTITY,
	Nome	VARCHAR(200) NOT NULL
)
GO

ALTER TABLE Perfil ADD CONSTRAINT PK_Perfil PRIMARY KEY(Id)
GO

CREATE TABLE Cliente(
	Id		INT IDENTITY,
	Nome	VARCHAR(200),
	Email	VARCHAR(200)
)
GO

ALTER TABLE Cliente ADD CONSTRAINT PK_Cliente PRIMARY KEY(Id)
GO

CREATE TABLE Compras( 
	Id	INT IDENTITY,
	IdCliente INT,
	Total FLOAT
)
GO

ALTER TABLE Compras ADD CONSTRAINT PK_Compras PRIMARY KEY(Id)
ALTER TABLE Compras ADD CONSTRAINT FK_Compras_Cliente FOREIGN KEY(IdCliente) REFERENCES Cliente(Id)
GO