//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_Email_Contato_id", "Contato", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DevMedia.Ed112.MVCSeguranca.EF.Entidade.Contato), "Email", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DevMedia.Ed112.MVCSeguranca.EF.Entidade.Email), true)]
[assembly: EdmRelationshipAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_RedeSocial_Contato_id", "Contato", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DevMedia.Ed112.MVCSeguranca.EF.Entidade.Contato), "RedeSocial", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DevMedia.Ed112.MVCSeguranca.EF.Entidade.RedeSocial), true)]
[assembly: EdmRelationshipAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_Telefone_Contato", "Contato", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DevMedia.Ed112.MVCSeguranca.EF.Entidade.Contato), "Telefone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DevMedia.Ed112.MVCSeguranca.EF.Entidade.Telefone), true)]
[assembly: EdmRelationshipAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_ResponsaUsuario", "Responsabilidade", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DevMedia.Ed112.MVCSeguranca.EF.Entidade.Responsabilidade), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DevMedia.Ed112.MVCSeguranca.EF.Entidade.Usuario), true)]

#endregion

namespace DevMedia.Ed112.MVCSeguranca.EF.Entidade
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Conexao : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Conexao object using the connection string found in the 'Conexao' section of the application configuration file.
        /// </summary>
        public Conexao() : base("name=Conexao", "Conexao")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Conexao object.
        /// </summary>
        public Conexao(string connectionString) : base(connectionString, "Conexao")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Conexao object.
        /// </summary>
        public Conexao(EntityConnection connection) : base(connection, "Conexao")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contato> Contato
        {
            get
            {
                if ((_Contato == null))
                {
                    _Contato = base.CreateObjectSet<Contato>("Contato");
                }
                return _Contato;
            }
        }
        private ObjectSet<Contato> _Contato;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Email> Email
        {
            get
            {
                if ((_Email == null))
                {
                    _Email = base.CreateObjectSet<Email>("Email");
                }
                return _Email;
            }
        }
        private ObjectSet<Email> _Email;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RedeSocial> RedeSocial
        {
            get
            {
                if ((_RedeSocial == null))
                {
                    _RedeSocial = base.CreateObjectSet<RedeSocial>("RedeSocial");
                }
                return _RedeSocial;
            }
        }
        private ObjectSet<RedeSocial> _RedeSocial;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Responsabilidade> Responsabilidade
        {
            get
            {
                if ((_Responsabilidade == null))
                {
                    _Responsabilidade = base.CreateObjectSet<Responsabilidade>("Responsabilidade");
                }
                return _Responsabilidade;
            }
        }
        private ObjectSet<Responsabilidade> _Responsabilidade;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Telefone> Telefone
        {
            get
            {
                if ((_Telefone == null))
                {
                    _Telefone = base.CreateObjectSet<Telefone>("Telefone");
                }
                return _Telefone;
            }
        }
        private ObjectSet<Telefone> _Telefone;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contato EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContato(Contato contato)
        {
            base.AddObject("Contato", contato);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Email EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmail(Email email)
        {
            base.AddObject("Email", email);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RedeSocial EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRedeSocial(RedeSocial redeSocial)
        {
            base.AddObject("RedeSocial", redeSocial);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Responsabilidade EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResponsabilidade(Responsabilidade responsabilidade)
        {
            base.AddObject("Responsabilidade", responsabilidade);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Telefone EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTelefone(Telefone telefone)
        {
            base.AddObject("Telefone", telefone);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DevMedia.Ed112.MVCSeguranca.EF.Entidades", Name="Contato")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contato : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contato object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nomeCompleto">Initial value of the nomeCompleto property.</param>
        /// <param name="apelido">Initial value of the apelido property.</param>
        public static Contato CreateContato(global::System.Int32 id, global::System.String nomeCompleto, global::System.String apelido)
        {
            Contato contato = new Contato();
            contato.id = id;
            contato.nomeCompleto = nomeCompleto;
            contato.apelido = apelido;
            return contato;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nomeCompleto
        {
            get
            {
                return _nomeCompleto;
            }
            set
            {
                OnnomeCompletoChanging(value);
                ReportPropertyChanging("nomeCompleto");
                _nomeCompleto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nomeCompleto");
                OnnomeCompletoChanged();
            }
        }
        private global::System.String _nomeCompleto;
        partial void OnnomeCompletoChanging(global::System.String value);
        partial void OnnomeCompletoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apelido
        {
            get
            {
                return _apelido;
            }
            set
            {
                OnapelidoChanging(value);
                ReportPropertyChanging("apelido");
                _apelido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apelido");
                OnapelidoChanged();
            }
        }
        private global::System.String _apelido;
        partial void OnapelidoChanging(global::System.String value);
        partial void OnapelidoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_Email_Contato_id", "Email")]
        public EntityCollection<Email> Email
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Email>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Email_Contato_id", "Email");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Email>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Email_Contato_id", "Email", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_RedeSocial_Contato_id", "RedeSocial")]
        public EntityCollection<RedeSocial> RedeSocial
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RedeSocial>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_RedeSocial_Contato_id", "RedeSocial");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RedeSocial>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_RedeSocial_Contato_id", "RedeSocial", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_Telefone_Contato", "Telefone")]
        public EntityCollection<Telefone> Telefone
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Telefone>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Telefone_Contato", "Telefone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Telefone>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Telefone_Contato", "Telefone", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DevMedia.Ed112.MVCSeguranca.EF.Entidades", Name="Email")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Email : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Email object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Email CreateEmail(global::System.Int32 id)
        {
            Email email = new Email();
            email.id = id;
            return email;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idContato
        {
            get
            {
                return _idContato;
            }
            set
            {
                OnidContatoChanging(value);
                ReportPropertyChanging("idContato");
                _idContato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idContato");
                OnidContatoChanged();
            }
        }
        private Nullable<global::System.Int32> _idContato;
        partial void OnidContatoChanging(Nullable<global::System.Int32> value);
        partial void OnidContatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String endereco
        {
            get
            {
                return _endereco;
            }
            set
            {
                OnenderecoChanging(value);
                ReportPropertyChanging("endereco");
                _endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("endereco");
                OnenderecoChanged();
            }
        }
        private global::System.String _endereco;
        partial void OnenderecoChanging(global::System.String value);
        partial void OnenderecoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_Email_Contato_id", "Contato")]
        public Contato Contato
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Email_Contato_id", "Contato").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Email_Contato_id", "Contato").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contato> ContatoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Email_Contato_id", "Contato");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Email_Contato_id", "Contato", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DevMedia.Ed112.MVCSeguranca.EF.Entidades", Name="RedeSocial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RedeSocial : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RedeSocial object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="urlPerfil">Initial value of the urlPerfil property.</param>
        /// <param name="nomeRedeSocial">Initial value of the nomeRedeSocial property.</param>
        public static RedeSocial CreateRedeSocial(global::System.Int32 id, global::System.String urlPerfil, global::System.String nomeRedeSocial)
        {
            RedeSocial redeSocial = new RedeSocial();
            redeSocial.id = id;
            redeSocial.urlPerfil = urlPerfil;
            redeSocial.nomeRedeSocial = nomeRedeSocial;
            return redeSocial;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idContato
        {
            get
            {
                return _idContato;
            }
            set
            {
                OnidContatoChanging(value);
                ReportPropertyChanging("idContato");
                _idContato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idContato");
                OnidContatoChanged();
            }
        }
        private Nullable<global::System.Int32> _idContato;
        partial void OnidContatoChanging(Nullable<global::System.Int32> value);
        partial void OnidContatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String urlPerfil
        {
            get
            {
                return _urlPerfil;
            }
            set
            {
                OnurlPerfilChanging(value);
                ReportPropertyChanging("urlPerfil");
                _urlPerfil = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("urlPerfil");
                OnurlPerfilChanged();
            }
        }
        private global::System.String _urlPerfil;
        partial void OnurlPerfilChanging(global::System.String value);
        partial void OnurlPerfilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nomeRedeSocial
        {
            get
            {
                return _nomeRedeSocial;
            }
            set
            {
                OnnomeRedeSocialChanging(value);
                ReportPropertyChanging("nomeRedeSocial");
                _nomeRedeSocial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nomeRedeSocial");
                OnnomeRedeSocialChanged();
            }
        }
        private global::System.String _nomeRedeSocial;
        partial void OnnomeRedeSocialChanging(global::System.String value);
        partial void OnnomeRedeSocialChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_RedeSocial_Contato_id", "Contato")]
        public Contato Contato
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_RedeSocial_Contato_id", "Contato").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_RedeSocial_Contato_id", "Contato").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contato> ContatoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_RedeSocial_Contato_id", "Contato");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_RedeSocial_Contato_id", "Contato", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DevMedia.Ed112.MVCSeguranca.EF.Entidades", Name="Responsabilidade")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Responsabilidade : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Responsabilidade object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Responsabilidade CreateResponsabilidade(global::System.Int32 id)
        {
            Responsabilidade responsabilidade = new Responsabilidade();
            responsabilidade.id = id;
            return responsabilidade;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_ResponsaUsuario", "Usuario")]
        public EntityCollection<Usuario> Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_ResponsaUsuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_ResponsaUsuario", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DevMedia.Ed112.MVCSeguranca.EF.Entidades", Name="Telefone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Telefone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Telefone object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="ddd">Initial value of the ddd property.</param>
        /// <param name="ddi">Initial value of the ddi property.</param>
        /// <param name="numero">Initial value of the numero property.</param>
        /// <param name="tipoTelefne">Initial value of the tipoTelefne property.</param>
        public static Telefone CreateTelefone(global::System.Int32 id, global::System.Int32 ddd, global::System.Int32 ddi, global::System.Int32 numero, global::System.Int32 tipoTelefne)
        {
            Telefone telefone = new Telefone();
            telefone.id = id;
            telefone.ddd = ddd;
            telefone.ddi = ddi;
            telefone.numero = numero;
            telefone.tipoTelefne = tipoTelefne;
            return telefone;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idContato
        {
            get
            {
                return _idContato;
            }
            set
            {
                OnidContatoChanging(value);
                ReportPropertyChanging("idContato");
                _idContato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idContato");
                OnidContatoChanged();
            }
        }
        private Nullable<global::System.Int32> _idContato;
        partial void OnidContatoChanging(Nullable<global::System.Int32> value);
        partial void OnidContatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ddd
        {
            get
            {
                return _ddd;
            }
            set
            {
                OndddChanging(value);
                ReportPropertyChanging("ddd");
                _ddd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ddd");
                OndddChanged();
            }
        }
        private global::System.Int32 _ddd;
        partial void OndddChanging(global::System.Int32 value);
        partial void OndddChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ddi
        {
            get
            {
                return _ddi;
            }
            set
            {
                OnddiChanging(value);
                ReportPropertyChanging("ddi");
                _ddi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ddi");
                OnddiChanged();
            }
        }
        private global::System.Int32 _ddi;
        partial void OnddiChanging(global::System.Int32 value);
        partial void OnddiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.Int32 _numero;
        partial void OnnumeroChanging(global::System.Int32 value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipoTelefne
        {
            get
            {
                return _tipoTelefne;
            }
            set
            {
                OntipoTelefneChanging(value);
                ReportPropertyChanging("tipoTelefne");
                _tipoTelefne = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipoTelefne");
                OntipoTelefneChanged();
            }
        }
        private global::System.Int32 _tipoTelefne;
        partial void OntipoTelefneChanging(global::System.Int32 value);
        partial void OntipoTelefneChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_Telefone_Contato", "Contato")]
        public Contato Contato
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Telefone_Contato", "Contato").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Telefone_Contato", "Contato").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contato> ContatoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Telefone_Contato", "Contato");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contato>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_Telefone_Contato", "Contato", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DevMedia.Ed112.MVCSeguranca.EF.Entidades", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="conta">Initial value of the conta property.</param>
        /// <param name="senha">Initial value of the senha property.</param>
        /// <param name="salt">Initial value of the salt property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String nome, global::System.String email, global::System.String conta, global::System.String senha, global::System.String salt)
        {
            Usuario usuario = new Usuario();
            usuario.id = id;
            usuario.nome = nome;
            usuario.email = email;
            usuario.conta = conta;
            usuario.senha = senha;
            usuario.salt = salt;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idResponsabilidade
        {
            get
            {
                return _idResponsabilidade;
            }
            set
            {
                OnidResponsabilidadeChanging(value);
                ReportPropertyChanging("idResponsabilidade");
                _idResponsabilidade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idResponsabilidade");
                OnidResponsabilidadeChanged();
            }
        }
        private Nullable<global::System.Int32> _idResponsabilidade;
        partial void OnidResponsabilidadeChanging(Nullable<global::System.Int32> value);
        partial void OnidResponsabilidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String conta
        {
            get
            {
                return _conta;
            }
            set
            {
                OncontaChanging(value);
                ReportPropertyChanging("conta");
                _conta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("conta");
                OncontaChanged();
            }
        }
        private global::System.String _conta;
        partial void OncontaChanging(global::System.String value);
        partial void OncontaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String salt
        {
            get
            {
                return _salt;
            }
            set
            {
                OnsaltChanging(value);
                ReportPropertyChanging("salt");
                _salt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("salt");
                OnsaltChanged();
            }
        }
        private global::System.String _salt;
        partial void OnsaltChanging(global::System.String value);
        partial void OnsaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DevMedia.Ed112.MVCSeguranca.EF.Entidades", "FK_ResponsaUsuario", "Responsabilidade")]
        public Responsabilidade Responsabilidade
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Responsabilidade>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_ResponsaUsuario", "Responsabilidade").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Responsabilidade>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_ResponsaUsuario", "Responsabilidade").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Responsabilidade> ResponsabilidadeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Responsabilidade>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_ResponsaUsuario", "Responsabilidade");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Responsabilidade>("DevMedia.Ed112.MVCSeguranca.EF.Entidades.FK_ResponsaUsuario", "Responsabilidade", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
