/*DICIONÁRIO DE DADOS DO ARTIGO LINQ TO SQL DA EASY .NET MAGAZINE EDIÇÃO 31 - Julho 2013
Autor: Luís Gabriel N. Simas
Data/Hora Início: 06/07/2013 - 23:00
Data/Hora Término: 07/07/2013 - 04:30
*/
/*Criação e uso do Banco de Dados*/
CREATE DATABASE ARTIGOGABRIEL_01
GO

USE ARTIGOGABRIEL_01
GO

/*Tabelas*/
CREATE TABLE Cliente(
	Id		INT	IDENTITY,
	Nome	VARCHAR(200) NOT NULL,
	Email	VARCHAR(30),
	idPais	INT NOT NULL
)

ALTER TABLE Cliente ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(Id)
ALTER TABLE Cliente ADD CONSTRAINT FK_CLIENTE FOREIGN KEY(IdPais) REFERENCES PAIS(Id)
GO

CREATE TABLE Pais(
	Id		INT IDENTITY,
	Nome	VARCHAR(100)
)
ALTER TABLE Pais ADD CONSTRAINT PK_PAIS PRIMARY KEY(Id)
GO

CREATE TABLE Pedido (
	Id			INT IDENTITY,
	IdCliente	INT NOT NULL,
	TotalPedido	FLOAT NOT NULL DEFAULT(0.00)
)
ALTER TABLE Pedido ADD CONSTRAINT PK_Pedido PRIMARY KEY(Id)
ALTER TABLE Pedido ADD CONSTRAINT FK_PED_CLI FOREIGN KEY(IdCliente) REFERENCES Cliente(Id)
GO
/**/
INSERT INTO Pais(Nome) VALUES('Brasil')
GO

INSERT INTO Cliente(Nome,Email,idPais) VALUES('Luis Gabriel','gabrielsimas@gmail.com',1)
GO
SELECT * FROM PAIS
GO

USE ARTIGOGABRIEL_01
GO
INSERT INTO Pedido(IdCliente, TotalPedido) VALUES (2,100.00)
INSERT INTO Pedido(IdCliente, TotalPedido) VALUES (2,200.00)
INSERT INTO Pedido(IdCliente, TotalPedido) VALUES (2,534.34)
GO